// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateAbsenceEntryData, CreateAbsenceEntryErrors, CreateAbsenceEntryResponses, CreateEmployeeData, CreateEmployeeErrors, CreateEmployeeResponses, CreateTimeEntryData, CreateTimeEntryErrors, CreateTimeEntryResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteAbsenceEntryData, DeleteAbsenceEntryErrors, DeleteAbsenceEntryResponses, DeleteEmployeeData, DeleteEmployeeErrors, DeleteEmployeeResponses, DeleteTimeEntryData, DeleteTimeEntryErrors, DeleteTimeEntryResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, GetAbsenceEntriesData, GetAbsenceEntriesErrors, GetAbsenceEntriesResponses, GetCurrentEmployeeData, GetCurrentEmployeeResponses, GetEmployeeByUserIdData, GetEmployeeByUserIdErrors, GetEmployeeByUserIdResponses, GetEmployeeHierarchyData, GetEmployeeHierarchyErrors, GetEmployeeHierarchyResponses, GetSetupStatusData, GetSetupStatusResponses, GetTimeEntriesData, GetTimeEntriesErrors, GetTimeEntriesResponses, GetUserByIdData, GetUserByIdErrors, GetUserByIdResponses, ListUsersData, ListUsersErrors, ListUsersResponses, LoginUserData, LoginUserErrors, LoginUserResponses, LogoutAllSessionsData, LogoutAllSessionsResponses, MeData, MeResponses, PatchUserData, PatchUserErrors, PatchUserResponses, ReadRootGetData, ReadRootGetResponses, RebuildEmployeeHierarchyData, RebuildEmployeeHierarchyErrors, RebuildEmployeeHierarchyResponses, RefreshTokensData, RefreshTokensResponses, RegisterUserData, RegisterUserErrors, RegisterUserResponses, RemoteLogoutAllSessionsData, RemoteLogoutAllSessionsErrors, RemoteLogoutAllSessionsResponses, RemoteResetPasswordData, RemoteResetPasswordErrors, RemoteResetPasswordResponses, SearchUsersData, SearchUsersErrors, SearchUsersResponses, SetupCreateData, SetupCreateErrors, SetupCreateResponses, UserIdExistsData, UserIdExistsErrors, UserIdExistsResponses, UsernameExistsData, UsernameExistsErrors, UsernameExistsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Me
 */
export const me = <ThrowOnError extends boolean = false>(options?: Options<MeData, ThrowOnError>) => {
    return (options?.client ?? client).get<MeResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/me/',
        ...options
    });
};

/**
 * List Users
 *
 * Get a list of all users. Optional filter by employee status.
 */
export const listUsers = <ThrowOnError extends boolean = false>(options: Options<ListUsersData, ThrowOnError>) => {
    return (options.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/',
        ...options
    });
};

/**
 * Create User
 *
 * Create a new user.
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
        url: '/users/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Search Users
 *
 * Search users by username. Optional filter by employee status. Superuser only.
 */
export const searchUsers = <ThrowOnError extends boolean = false>(options: Options<SearchUsersData, ThrowOnError>) => {
    return (options.client ?? client).get<SearchUsersResponses, SearchUsersErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/search',
        ...options
    });
};

/**
 * Delete User
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Get User By Id
 */
export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserByIdResponses, GetUserByIdErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options
    });
};

/**
 * Patch User
 */
export const patchUser = <ThrowOnError extends boolean = false>(options: Options<PatchUserData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchUserResponses, PatchUserErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * User Id Exists
 */
export const userIdExists = <ThrowOnError extends boolean = false>(options: Options<UserIdExistsData, ThrowOnError>) => {
    return (options.client ?? client).get<UserIdExistsResponses, UserIdExistsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/exists/{id}',
        ...options
    });
};

/**
 * Username Exists
 */
export const usernameExists = <ThrowOnError extends boolean = false>(options: Options<UsernameExistsData, ThrowOnError>) => {
    return (options.client ?? client).get<UsernameExistsResponses, UsernameExistsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/exists/username/{name}',
        ...options
    });
};

/**
 * Register User
 */
export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>({
        url: '/auth/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login User
 */
export const loginUser = <ThrowOnError extends boolean = false>(options: Options<LoginUserData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginUserResponses, LoginUserErrors, ThrowOnError>({
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout All Sessions
 *
 * Logs out from all devices by rotating the token key (invalidates all tokens).
 */
export const logoutAllSessions = <ThrowOnError extends boolean = false>(options?: Options<LogoutAllSessionsData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutAllSessionsResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/logout-all',
        ...options
    });
};

/**
 * Refresh Tokens
 *
 * Refreshes both access and refresh tokens using a valid refresh token.
 */
export const refreshTokens = <ThrowOnError extends boolean = false>(options?: Options<RefreshTokensData, ThrowOnError>) => {
    return (options?.client ?? client).post<RefreshTokensResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/refresh',
        ...options
    });
};

/**
 * Change Password
 *
 * Changes the current user's password and invalidates existing tokens.
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => {
    return (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/change-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Remote Logout All Sessions
 *
 * Logs out from all devices by rotating the token key (invalidates all tokens).
 */
export const remoteLogoutAllSessions = <ThrowOnError extends boolean = false>(options: Options<RemoteLogoutAllSessionsData, ThrowOnError>) => {
    return (options.client ?? client).post<RemoteLogoutAllSessionsResponses, RemoteLogoutAllSessionsErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/remote-logout-all',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Remote Reset Password
 */
export const remoteResetPassword = <ThrowOnError extends boolean = false>(options: Options<RemoteResetPasswordData, ThrowOnError>) => {
    return (options.client ?? client).post<RemoteResetPasswordResponses, RemoteResetPasswordErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/auth/remote-reset-password',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Current Employee
 */
export const getCurrentEmployee = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentEmployeeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetCurrentEmployeeResponses, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/me',
        ...options
    });
};

/**
 * Get Employee Hierarchy
 *
 * Get hierarchy information for an employee including supervisors and subordinates.
 */
export const getEmployeeHierarchy = <ThrowOnError extends boolean = false>(options: Options<GetEmployeeHierarchyData, ThrowOnError>) => {
    return (options.client ?? client).get<GetEmployeeHierarchyResponses, GetEmployeeHierarchyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/{user_id}/hierarchy',
        ...options
    });
};

/**
 * Delete Employee
 *
 * Delete an employee and heal the hierarchy (superuser only).
 */
export const deleteEmployee = <ThrowOnError extends boolean = false>(options: Options<DeleteEmployeeData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteEmployeeResponses, DeleteEmployeeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/{user_id}',
        ...options
    });
};

/**
 * Get Employee By User Id
 */
export const getEmployeeByUserId = <ThrowOnError extends boolean = false>(options: Options<GetEmployeeByUserIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetEmployeeByUserIdResponses, GetEmployeeByUserIdErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/{user_id}',
        ...options
    });
};

/**
 * Create Employee
 */
export const createEmployee = <ThrowOnError extends boolean = false>(options: Options<CreateEmployeeData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateEmployeeResponses, CreateEmployeeErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Rebuild Employee Hierarchy
 *
 * Rebuild the entire employee hierarchy table (superuser only).
 */
export const rebuildEmployeeHierarchy = <ThrowOnError extends boolean = false>(options?: Options<RebuildEmployeeHierarchyData, ThrowOnError>) => {
    return (options?.client ?? client).post<RebuildEmployeeHierarchyResponses, RebuildEmployeeHierarchyErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/employees/__rebuild_hierarchy',
        ...options
    });
};

/**
 * Delete Time Entry
 */
export const deleteTimeEntry = <ThrowOnError extends boolean = false>(options: Options<DeleteTimeEntryData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteTimeEntryResponses, DeleteTimeEntryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/time_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Time Entries
 *
 * Get time entries for an employee by ID, date, or date range.
 */
export const getTimeEntries = <ThrowOnError extends boolean = false>(options: Options<GetTimeEntriesData, ThrowOnError>) => {
    return (options.client ?? client).get<GetTimeEntriesResponses, GetTimeEntriesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/time_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Time Entry
 *
 * Create a time entry for an employee.
 */
export const createTimeEntry = <ThrowOnError extends boolean = false>(options: Options<CreateTimeEntryData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateTimeEntryResponses, CreateTimeEntryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/time_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Absence Entry
 */
export const deleteAbsenceEntry = <ThrowOnError extends boolean = false>(options: Options<DeleteAbsenceEntryData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteAbsenceEntryResponses, DeleteAbsenceEntryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/absence_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Absence Entries
 *
 * Get absence entries for an employee by ID, date, or date range.
 */
export const getAbsenceEntries = <ThrowOnError extends boolean = false>(options: Options<GetAbsenceEntriesData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAbsenceEntriesResponses, GetAbsenceEntriesErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/absence_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create Absence Entry
 *
 * Create an absence entry for an employee.
 */
export const createAbsenceEntry = <ThrowOnError extends boolean = false>(options: Options<CreateAbsenceEntryData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAbsenceEntryResponses, CreateAbsenceEntryErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/absence_entries/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Setup Status
 */
export const getSetupStatus = <ThrowOnError extends boolean = false>(options?: Options<GetSetupStatusData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSetupStatusResponses, unknown, ThrowOnError>({
        url: '/__setup/',
        ...options
    });
};

/**
 * Setup Create
 */
export const setupCreate = <ThrowOnError extends boolean = false>(options: Options<SetupCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<SetupCreateResponses, SetupCreateErrors, ThrowOnError>({
        url: '/__setup/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};
