// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

/**
 * AbsenceEntry
 */
export type AbsenceEntry = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: string;
    entry_type: AbsenceEntryType;
    /**
     * Date Begin
     */
    date_begin: string;
    /**
     * Date End
     */
    date_end: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * AbsenceEntryCreate
 */
export type AbsenceEntryCreate = {
    /**
     * User Id
     */
    user_id: string;
    entry_type: AbsenceEntryType;
    /**
     * Date Begin
     */
    date_begin: string;
    /**
     * Date End
     */
    date_end: string;
};

/**
 * AbsenceEntryDelete
 */
export type AbsenceEntryDelete = {
    /**
     * Id
     */
    id: number;
};

/**
 * AbsenceEntryGet
 */
export type AbsenceEntryGet = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Date
     */
    date?: null;
    /**
     * From Date
     */
    from_date?: null;
    /**
     * To Date
     */
    to_date?: null;
};

/**
 * AbsenceEntryType
 */
export type AbsenceEntryType = 'sickness' | 'vacation' | 'other';

/**
 * EmployeeCreate
 */
export type EmployeeCreate = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birthday
     */
    birthday: string;
    hour_model: HourModel;
    /**
     * Pause Time Minutes
     */
    pause_time_minutes: number;
    /**
     * Start From
     */
    start_from: string;
};

/**
 * GetSetupStatus
 */
export type GetSetupStatus = {
    /**
     * Is Setup
     */
    is_setup: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HierarchyNode
 *
 * Represents a node in the employee hierarchy.
 */
export type HierarchyNode = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Username
     */
    username: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Supervisor Id
     */
    supervisor_id?: string | null;
    /**
     * Depth
     */
    depth: number;
};

/**
 * HierarchyRebuildResponse
 *
 * Response from hierarchy rebuild endpoint.
 */
export type HierarchyRebuildResponse = {
    /**
     * Success
     */
    success: boolean;
    /**
     * Message
     */
    message: string;
    stats: HierarchyRebuildStats;
};

/**
 * HierarchyRebuildStats
 *
 * Statistics from a hierarchy rebuild operation.
 */
export type HierarchyRebuildStats = {
    /**
     * Records Deleted
     */
    records_deleted: number;
    /**
     * Records Created
     */
    records_created: number;
    /**
     * Employees Processed
     */
    employees_processed: number;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
};

/**
 * HierarchyResponse
 *
 * Response containing hierarchy information for an employee.
 */
export type HierarchyResponse = {
    employee: HierarchyNode;
    /**
     * Supervisors
     */
    supervisors: Array<HierarchyNode>;
    /**
     * Subordinates
     */
    subordinates: Array<HierarchyNode>;
};

/**
 * HourModel
 */
export type HourModel = 6 | 7 | 8;

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MeUser
 */
export type MeUser = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Created At
     */
    created_at: string;
    employee: AppSchemasMeEmployee | null;
};

/**
 * PagedResult
 */
export type PagedResultListUserInfo = {
    /**
     * Page
     */
    page: Array<UserInfo>;
    /**
     * Total
     */
    total: number;
};

/**
 * PasswordChangeRequest
 */
export type PasswordChangeRequest = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * RemoteLogoutAllRequest
 */
export type RemoteLogoutAllRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * RemoteResetPasswordRequest
 */
export type RemoteResetPasswordRequest = {
    /**
     * User Id
     */
    user_id: string;
};

/**
 * RemoteResetPasswordResponse
 */
export type RemoteResetPasswordResponse = {
    /**
     * New Password
     */
    new_password: string;
};

/**
 * ServerStoreCreate
 */
export type ServerStoreCreate = {
    /**
     * Timezone
     */
    timezone: string;
};

/**
 * SetupCreate
 */
export type SetupCreate = {
    user: UserCreate;
    server_store: ServerStoreCreate;
};

/**
 * TimeEntry
 */
export type TimeEntry = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * User Id
     */
    user_id: string;
    entry_type: TimeEntryType;
    /**
     * Date Time
     */
    date_time: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created At
     */
    created_at?: string;
};

/**
 * TimeEntryCreate
 */
export type TimeEntryCreate = {
    /**
     * User Id
     */
    user_id: string;
    entry_type: TimeEntryType;
    /**
     * Date Time
     */
    date_time: string;
};

/**
 * TimeEntryDelete
 */
export type TimeEntryDelete = {
    /**
     * Id
     */
    id: number;
};

/**
 * TimeEntryGet
 */
export type TimeEntryGet = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * Id
     */
    id: number | null;
    /**
     * Date
     */
    date: string | null;
    /**
     * From Date
     */
    from_date: string | null;
    /**
     * To Date
     */
    to_date: string | null;
};

/**
 * TimeEntryType
 */
export type TimeEntryType = 'arrival' | 'departure';

/**
 * TokenPair
 */
export type TokenPair = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Refresh Token
     */
    refresh_token: string;
    token_type?: TokenType;
};

/**
 * TokenType
 */
export type TokenType = 'bearer';

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserEmployeeOnly
 */
export type UserEmployeeOnly = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birthday
     */
    birthday: string;
};

/**
 * UserEmployeePatch
 */
export type UserEmployeePatch = {
    /**
     * New First Name
     */
    new_first_name?: string | null;
    /**
     * New Last Name
     */
    new_last_name?: string | null;
    /**
     * New Birthday
     */
    new_birthday?: string | null;
    /**
     * New Supervisor Id
     */
    new_supervisor_id?: string | null;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Is Superuser
     */
    is_superuser: boolean;
    /**
     * Created At
     */
    created_at: string;
    employee?: UserEmployeeOnly | null;
};

/**
 * UserPatch
 */
export type UserPatch = {
    /**
     * New Username
     */
    new_username?: string | null;
    /**
     * New Is Superuser
     */
    new_is_superuser?: boolean | null;
    new_employee?: UserEmployeePatch | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Employee
 */
export type AppModelsEmployeeEmployee = {
    /**
     * User Id
     */
    user_id: string;
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Supervisor Id
     */
    supervisor_id?: string | null;
    /**
     * Birthday
     */
    birthday: string;
    hour_model: HourModel;
    /**
     * Pause Time Minutes
     */
    pause_time_minutes: number;
    /**
     * Start From
     */
    start_from: string;
};

/**
 * Employee
 */
export type AppSchemasMeEmployee = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
    /**
     * Birthday
     */
    birthday: string;
};

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me/';
};

export type MeResponses = {
    /**
     * Successful Response
     */
    200: MeUser;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page
         */
        page: number;
        /**
         * Page Size
         */
        page_size: number;
        /**
         * Is Employee
         */
        is_employee?: boolean | null;
    };
    url: '/users/';
};

export type ListUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * Successful Response
     */
    200: PagedResultListUserInfo;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/users/';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserInfo;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type SearchUsersData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Query
         */
        query: string;
        /**
         * Page
         */
        page: number;
        /**
         * Page Size
         */
        page_size: number;
        /**
         * Is Employee
         */
        is_employee?: boolean | null;
    };
    url: '/users/search';
};

export type SearchUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchUsersError = SearchUsersErrors[keyof SearchUsersErrors];

export type SearchUsersResponses = {
    /**
     * Successful Response
     */
    200: PagedResultListUserInfo;
};

export type SearchUsersResponse = SearchUsersResponses[keyof SearchUsersResponses];

export type DeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserError = DeleteUserErrors[keyof DeleteUserErrors];

export type DeleteUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetUserByIdData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type PatchUserData = {
    body: UserPatch;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PatchUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchUserError = PatchUserErrors[keyof PatchUserErrors];

export type PatchUserResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UserIdExistsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/exists/{id}';
};

export type UserIdExistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UserIdExistsError = UserIdExistsErrors[keyof UserIdExistsErrors];

export type UserIdExistsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UsernameExistsData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/users/exists/username/{name}';
};

export type UsernameExistsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsernameExistsError = UsernameExistsErrors[keyof UsernameExistsErrors];

export type UsernameExistsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginUserData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutAllSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout-all';
};

export type LogoutAllSessionsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutAllSessionsResponse = LogoutAllSessionsResponses[keyof LogoutAllSessionsResponses];

export type RefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokensResponses = {
    /**
     * Successful Response
     */
    200: TokenPair;
};

export type RefreshTokensResponse = RefreshTokensResponses[keyof RefreshTokensResponses];

export type ChangePasswordData = {
    body: PasswordChangeRequest;
    path?: never;
    query?: never;
    url: '/auth/change-password';
};

export type ChangePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangePasswordError = ChangePasswordErrors[keyof ChangePasswordErrors];

export type ChangePasswordResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type RemoteLogoutAllSessionsData = {
    body: RemoteLogoutAllRequest;
    path?: never;
    query?: never;
    url: '/auth/remote-logout-all';
};

export type RemoteLogoutAllSessionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoteLogoutAllSessionsError = RemoteLogoutAllSessionsErrors[keyof RemoteLogoutAllSessionsErrors];

export type RemoteLogoutAllSessionsResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RemoteLogoutAllSessionsResponse = RemoteLogoutAllSessionsResponses[keyof RemoteLogoutAllSessionsResponses];

export type RemoteResetPasswordData = {
    body: RemoteResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/auth/remote-reset-password';
};

export type RemoteResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RemoteResetPasswordError = RemoteResetPasswordErrors[keyof RemoteResetPasswordErrors];

export type RemoteResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: RemoteResetPasswordResponse;
};

export type RemoteResetPasswordResponse2 = RemoteResetPasswordResponses[keyof RemoteResetPasswordResponses];

export type GetCurrentEmployeeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/employees/me';
};

export type GetCurrentEmployeeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetEmployeeHierarchyData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/employees/{user_id}/hierarchy';
};

export type GetEmployeeHierarchyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEmployeeHierarchyError = GetEmployeeHierarchyErrors[keyof GetEmployeeHierarchyErrors];

export type GetEmployeeHierarchyResponses = {
    /**
     * Successful Response
     */
    200: HierarchyResponse;
};

export type GetEmployeeHierarchyResponse = GetEmployeeHierarchyResponses[keyof GetEmployeeHierarchyResponses];

export type DeleteEmployeeData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/employees/{user_id}';
};

export type DeleteEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteEmployeeError = DeleteEmployeeErrors[keyof DeleteEmployeeErrors];

export type DeleteEmployeeResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEmployeeResponse = DeleteEmployeeResponses[keyof DeleteEmployeeResponses];

export type GetEmployeeByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/employees/{user_id}';
};

export type GetEmployeeByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEmployeeByUserIdError = GetEmployeeByUserIdErrors[keyof GetEmployeeByUserIdErrors];

export type GetEmployeeByUserIdResponses = {
    /**
     * Response Getemployeebyuserid
     *
     * Successful Response
     */
    200: AppModelsEmployeeEmployee | null;
};

export type GetEmployeeByUserIdResponse = GetEmployeeByUserIdResponses[keyof GetEmployeeByUserIdResponses];

export type CreateEmployeeData = {
    body: EmployeeCreate;
    path?: never;
    query?: never;
    url: '/employees/';
};

export type CreateEmployeeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateEmployeeError = CreateEmployeeErrors[keyof CreateEmployeeErrors];

export type CreateEmployeeResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type RebuildEmployeeHierarchyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Force
         *
         * Force rebuild without pre-validation checks
         */
        force?: boolean;
    };
    url: '/employees/__rebuild_hierarchy';
};

export type RebuildEmployeeHierarchyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RebuildEmployeeHierarchyError = RebuildEmployeeHierarchyErrors[keyof RebuildEmployeeHierarchyErrors];

export type RebuildEmployeeHierarchyResponses = {
    /**
     * Successful Response
     */
    200: HierarchyRebuildResponse;
};

export type RebuildEmployeeHierarchyResponse = RebuildEmployeeHierarchyResponses[keyof RebuildEmployeeHierarchyResponses];

export type DeleteTimeEntryData = {
    body: TimeEntryDelete;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean | null;
    };
    url: '/time_entries/';
};

export type DeleteTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTimeEntryError = DeleteTimeEntryErrors[keyof DeleteTimeEntryErrors];

export type DeleteTimeEntryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteTimeEntryResponse = DeleteTimeEntryResponses[keyof DeleteTimeEntryResponses];

export type CreateTimeEntryData = {
    body: TimeEntryCreate;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/time_entries/';
};

export type CreateTimeEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTimeEntryError = CreateTimeEntryErrors[keyof CreateTimeEntryErrors];

export type CreateTimeEntryResponses = {
    /**
     * Successful Response
     */
    201: TimeEntry;
};

export type CreateTimeEntryResponse = CreateTimeEntryResponses[keyof CreateTimeEntryResponses];

export type GetTimeEntriesData = {
    body: TimeEntryGet;
    path?: never;
    query?: never;
    url: '/time_entries/get';
};

export type GetTimeEntriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimeEntriesError = GetTimeEntriesErrors[keyof GetTimeEntriesErrors];

export type GetTimeEntriesResponses = {
    /**
     * Response Gettimeentries
     *
     * Successful Response
     */
    200: TimeEntry | Array<TimeEntry> | null;
};

export type GetTimeEntriesResponse = GetTimeEntriesResponses[keyof GetTimeEntriesResponses];

export type DeleteAbsenceEntryData = {
    body: AbsenceEntryDelete;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean | null;
    };
    url: '/absence_entries/';
};

export type DeleteAbsenceEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAbsenceEntryError = DeleteAbsenceEntryErrors[keyof DeleteAbsenceEntryErrors];

export type DeleteAbsenceEntryResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteAbsenceEntryResponse = DeleteAbsenceEntryResponses[keyof DeleteAbsenceEntryResponses];

export type GetAbsenceEntriesData = {
    body: AbsenceEntryGet;
    path?: never;
    query?: never;
    url: '/absence_entries/';
};

export type GetAbsenceEntriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAbsenceEntriesError = GetAbsenceEntriesErrors[keyof GetAbsenceEntriesErrors];

export type GetAbsenceEntriesResponses = {
    /**
     * Response Getabsenceentries
     *
     * Successful Response
     */
    200: AbsenceEntry | Array<AbsenceEntry> | null;
};

export type GetAbsenceEntriesResponse = GetAbsenceEntriesResponses[keyof GetAbsenceEntriesResponses];

export type CreateAbsenceEntryData = {
    body: AbsenceEntryCreate;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
        /**
         * Dry
         */
        dry?: boolean;
    };
    url: '/absence_entries/';
};

export type CreateAbsenceEntryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAbsenceEntryError = CreateAbsenceEntryErrors[keyof CreateAbsenceEntryErrors];

export type CreateAbsenceEntryResponses = {
    /**
     * Successful Response
     */
    201: AbsenceEntry;
};

export type CreateAbsenceEntryResponse = CreateAbsenceEntryResponses[keyof CreateAbsenceEntryResponses];

export type GetSetupStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/__setup/';
};

export type GetSetupStatusResponses = {
    /**
     * Successful Response
     */
    201: GetSetupStatus;
};

export type GetSetupStatusResponse = GetSetupStatusResponses[keyof GetSetupStatusResponses];

export type SetupCreateData = {
    body: SetupCreate;
    path?: never;
    query?: never;
    url: '/__setup/';
};

export type SetupCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetupCreateError = SetupCreateErrors[keyof SetupCreateErrors];

export type SetupCreateResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
