name: Tests

on:
  # Run on push to main branch
  push:
    branches:
      - main

  # Run on pull requests to main branch
  pull_request:
    branches:
      - main

  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: actions/setup-node@v6
        with:
          node-version: '25'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --include=dev

      - name: Build
        run: npm run build
